language: node_js
sudo: false
dist: trusty
os:
  - osx
node_js:
  - "10"
  - "8"
script:
  - npm run test:ci
jobs:
  include:
    - os: linux
      before_script: 
        - echo "Add code-climate exporter ..."
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT