language: node_js
sudo: false
dist: trusty
os:
  - linux
  - osx
node_js:
  - "10"
  - "8"
before_script:
  - echo $CC_TEST_REPORTER_ID
  - >
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo "Add code-climate exporter ..."
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
      fi
script:
  - npm run test:ci
after_script:
  - >
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      fi
jobs:
  include:
    - os: windows
      filter_secrets: false